### ISSUE TITLE
[meta] WebDAV storage quota

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-katana#235]
* [ ] Admin could see the quota of a principal,
* [ ] Admin could resize the quota,
* [ ] Admin could remove a file or a directory.
