### ISSUE TITLE
[meta] Auto-update

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-katana#32]
It could be awesome to have something to auto-update katana. It will ease the adoption of the software.

:warning: Edit

Here is the plan.
## Stub
- [x] `katana stub --zip` to produce a ZIP archive,
- [x] `katana stub --phar` to produce a PHAR,

The resulting ZIP will be a regular one.
The resulting PHAR will be executable. We should be able to run:
- [x] `./katana.phar --metadata` to get all the metadata about the archive (author, license, datetime etc.),
- [x] `./katana.phar --signature` to get the signature (sum) of the archive (needed to the security),
- [x] `./katana.phar --list` to list the content of the archive (bonus),
- [x] `./katana.phar --extract .` and `--overwrite` to extract the archive somewhere.
## Update

Installation will be done with Git or a ZIP archive. Update can be done with the same process. Needed command:
- [x] `katana update --fetch` to check if new update**s** are available (if yes, downloaded in `data/share/`, so we should add `--zip` and `--phar` here). :warning: Edit: we use `--fetch` and `--fetch-zip` and the output directory is `data/share/update/`.
## Auto-update

However, auto-update will be based on the PHAR archive. Why? Because of the `--extract` option on the executable PHAR that allows us to auto-extract the archive. Still by using the `update` command:
- [x] `katana update --apply` to apply the downloaded updates. Without no argument, will apply all of them, with an argument, will apply only the selected one. :warning: Edit: `--apply` requires a path so far, full-automation is dangerous sometimes, start easy.
## No combo update

We have to apply update gradually, one after the other. No update scripts yet, can be introduced later.
