### ISSUE TITLE
[meta] Installation

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-katana#5]
This is a meta issue to track the progression of the installation wizzard.

Progression 1:
- [x] set a flag representing whether sabre/katana has been installed or not,
- [x] `install.php` must redirect to `index.php` if installed,
- [x] `index.php` must redirect to `install.php` if not installed,
- [x] install from CLI runs if not installed.

Progression 2:
- [x] choose a database,
- [x] install schemas,
- [x] choose an administrator password,
- [x] choose the base URL.
