### ISSUE TITLE
[meta] Administration

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-katana#6]
This is a meta issue to track the progression of the administration panel/backend.

Iterations:
- [x] 1. global UI, basic users support with fixtures,
- [x] 2. login support,
- [x] 3. move inline Javascript and Handlebar views into files,
- [x] 4. users validation,
- [x] 5. auto-detect the base URL,
- [x] 6. replace fixtures by real data (server API).
